name: quiz
description: "Quiz Game Application"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: 6.1.2
  confetti: 0.8.0
  just_audio: 0.9.46

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  path_provider: 2.1.5

flutter:
  assets:
    - assets/sounds/correct.mp3
    - assets/sounds/error.mp3

  uses-material-design: true